#!/bin/bash

# install extension using pip
python -m pip install .

# remove unnecessary directories when using the binder
rm -rf src
rm -rf style
rm -rf design
rm -rf .github
rm -rf binder
rm -rf docs
rm -rf jupyterlab_interactive_dashboard_editor
rm package.json
rm tsconfig.json
rm yarn.lock
rm MANIFEST.in
rm pyproject.toml
rm setup.py

jupyter lab clean
